"""
load_case_dictionary.py — Load case-specific proper nouns from CR-provided dictionary files.

Supports:
  - CaseCATalyst .tlx files (game-day word list, one word per line with flag)
  - Plain text CASE_DICTIONARY.txt (one word per line, any format)

Graceful degradation: returns empty list if no dictionary found.
Pipeline never breaks without it — it just runs without the enhancement.

Usage:
  from load_case_dictionary import load_case_dictionary
  proper_nouns = load_case_dictionary()   # returns list of strings

Onboarding note:
  Ask CAT reporters to include the .tlx file with each job submission.
  It's auto-generated by CaseCATalyst — zero extra work for the CR.
  If they have a full master dictionary (.sgdct), that works too.
"""

import os
import re
import glob


def load_case_dictionary(search_dir=None):
    """
    Load case-specific proper nouns from available dictionary files.

    Priority:
      1. CASE_DICTIONARY.txt  (manually curated, if present)
      2. *.tlx                (CaseCATalyst game-day word list)
      3. Nothing found        → return []

    Returns: sorted list of proper noun strings (deduplicated).
    """
    if search_dir is None:
        search_dir = os.path.dirname(os.path.abspath(__file__))

    words = []

    # ── Priority 1: CASE_DICTIONARY.txt ──────────────────────────────────────
    manual_path = os.path.join(search_dir, 'CASE_DICTIONARY.txt')
    if os.path.exists(manual_path):
        words.extend(_load_plain_text(manual_path))
        print(f'  [DICT] Loaded CASE_DICTIONARY.txt  ({len(words)} words)')
        return _dedupe(words)

    # ── Priority 2: .tlx file ─────────────────────────────────────────────────
    tlx_files = glob.glob(os.path.join(search_dir, '*.tlx'))
    if tlx_files:
        for tlx in tlx_files:
            new_words = _load_tlx(tlx)
            words.extend(new_words)
            print(f'  [DICT] Loaded {os.path.basename(tlx)}  ({len(new_words)} words)')
        return _dedupe(words)

    # ── Nothing found ─────────────────────────────────────────────────────────
    print('  [DICT] No dictionary file found — running without case-specific proper nouns.')
    print('         TIP: Ask CR to include their .tlx game-day word file with each job.')
    return []


def _load_tlx(path):
    """
    Parse CaseCATalyst .tlx translation exception file.
    Format:
        #LID 12345
        WordOne   i
        AnotherWord   i
    Lines starting with # are comments.
    The flag column (i = include/ignore) is ignored — all words are extracted.
    """
    words = []
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            # Split on whitespace — first token is the word, rest is flag
            parts = line.split()
            if parts:
                word = parts[0].strip()
                if word and len(word) >= 2:
                    words.append(word)
    return words


def _load_plain_text(path):
    """Parse plain text dictionary file — one word/phrase per line."""
    words = []
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            word = line.strip()
            if word and not word.startswith('#'):
                words.append(word)
    return words


def _dedupe(words):
    """Deduplicate and sort, preserving original case."""
    seen = set()
    result = []
    for w in words:
        key = w.lower()
        if key not in seen:
            seen.add(key)
            result.append(w)
    return sorted(result)


def build_dictionary_prompt_block(words):
    """
    Format the proper noun list as a system prompt injection block for ai_engine.py.
    Returns empty string if words list is empty.
    """
    if not words:
        return ''
    word_list = '\n'.join(f'  - {w}' for w in words)
    return f"""

══════════════════════════════════════════════════════════════════════════════
CASE-SPECIFIC PROPER NOUNS — DO NOT ALTER THESE SPELLINGS
══════════════════════════════════════════════════════════════════════════════

The following proper nouns appear in this deposition. They were provided by
the court reporter's own CaseCATalyst dictionary for this specific case.
Their spelling is AUTHORITATIVE. Do NOT "correct" them, even if they look
unusual. Preserve exact capitalization.

{word_list}

If any of these words appear garbled in the steno (e.g. "Sybulski" for
"Cibulsky"), correct them to the authoritative spelling above.
"""


if __name__ == '__main__':
    # Quick test
    words = load_case_dictionary()
    print(f'Loaded {len(words)} proper nouns:')
    for w in words:
        print(f'  {w}')
