"""
new_job.py — Bridge from intake folder to engine run.

Usage:
    python new_job.py --cr dalotto_ny_001 --job fourman_wcb_20260324

What it does:
    1. Reads  data/cr_profiles/[cr]/[job]/intake/CASE_INFO.json
    2. Reads  data/cr_profiles/[cr]/CR_PROFILE.json
    3. Builds data/cr_profiles/[cr]/[job]/work/CASE_CAPTION.json
    4. Copies RTF from intake/ into engine directory
    5. Writes cr_config.json for this CR
    6. Updates JOB_STATUS.md (staged)
    7. Prints the exact run command — no guessing

Data root: C:\\depo_transformation\\data  (or set DEPO_ROOT env var)
Engine dir: directory this script lives in
"""

import os
import sys
import json
import shutil
import argparse
from datetime import datetime

# ─────────────────────────────────────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────────────────────────────────────

ENGINE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_ROOT  = os.environ.get('DEPO_ROOT', r'C:\depo_transformation\data')


def cr_dir(cr_id):
    return os.path.join(DATA_ROOT, 'cr_profiles', cr_id)

def job_dir(cr_id, job_id):
    return os.path.join(cr_dir(cr_id), job_id)

def intake_dir(cr_id, job_id):
    return os.path.join(job_dir(cr_id, job_id), 'intake')

def work_dir(cr_id, job_id):
    return os.path.join(job_dir(cr_id, job_id), 'work')


# ─────────────────────────────────────────────────────────────────────────────
# LOAD
# ─────────────────────────────────────────────────────────────────────────────

def load_json(path, label):
    if not os.path.exists(path):
        print(f'  ERROR: {label} not found at {path}')
        sys.exit(1)
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


# ─────────────────────────────────────────────────────────────────────────────
# BUILD CASE_CAPTION.json
# State-aware: NY WC and Louisiana have different fields.
# ─────────────────────────────────────────────────────────────────────────────

def build_case_caption(case_info, cr_profile, job_id):
    """
    Translate CASE_INFO.json (CR's intake form) into CASE_CAPTION.json
    (engine-ready case data). State-aware.
    """
    state   = cr_profile.get('state', '').upper()
    witness = case_info.get('witness', {})
    case    = case_info.get('case', {})
    depo    = case_info.get('depo', {})
    atty    = case_info.get('attorneys', [])

    # Witness name — combine name + credentials
    w_name = witness.get('name', 'UNKNOWN WITNESS')
    w_cred = witness.get('credentials', '')
    witness_full = f"{w_name}, {w_cred}".strip(', ') if w_cred else w_name

    # Examining attorney — first attorney listed
    examining = ''
    if atty:
        by_line = atty[0].get('by', '')
        last = by_line.split(',')[0].split()[-1] if by_line else ''
        examining = f'MR. {last.upper()}' if last else ''

    caption = {
        '_source':       f'Generated by new_job.py from intake/CASE_INFO.json — {datetime.now().strftime("%Y-%m-%d")}',
        '_note':         'AUTHORITATIVE case data for this job. Edit here, not in CASE_INFO.json.',
        '_last_updated': datetime.now().strftime('%Y-%m-%d'),
        'case_short':    job_id,
        'state':         state,
        'cr_id':         cr_profile.get('cr_id'),
        'witness_name':  witness_full.upper(),
        'witness_last':  w_name.split()[-1].upper(),
        'depo_type':     depo.get('type', 'DEPOSITION'),
        'witness_role':  witness.get('role', ''),
        'depo_date':     depo.get('date', ''),
        'depo_date_short': depo.get('date', ''),
        'depo_time':     depo.get('time', ''),
        'reporter_name': cr_profile.get('cr_name', '').upper(),
        'reporter_name_display': cr_profile.get('cr_name_display', cr_profile.get('cr_name', '')),
        'reporter_title': cr_profile.get('title', ''),
        'reporter_credential_1': cr_profile.get('credential_letters'),
        'reporter_credential_2': None,
        'reporter_address': cr_profile.get('address', ''),
        'reporter_phone':   cr_profile.get('phone', ''),
        'reporter_license': cr_profile.get('notary_reg_number', ''),
        'examining_atty': examining,
        'appearances':    _build_appearances(atty),
        'exhibit_list':   [],
    }

    # State-specific fields
    if state == 'NY':
        caption.update({
            'wcb_case_no':    case.get('wcb_number', ''),
            'carrier_case_no': case.get('carrier_number', ''),
            'date_of_accident': case.get('date_of_accident', ''),
            'claimant':       case.get('claimant', '').upper(),
            'claimant_role':  'Claimant,',
            'employer':       case.get('employer', '').upper(),
            'employer_role':  'Employer.',
        })
    elif state == 'LA':
        caption.update({
            'plaintiff':      case.get('plaintiff', '').upper(),
            'plaintiff_role': 'Plaintiffs,',
            'defendant':      case.get('defendant', '').upper(),
            'defendant_role': 'Defendants.',
            'docket':         case.get('docket', ''),
            'division':       case.get('division', ''),
            'parish':         case.get('parish', '').upper(),
            'court':          case.get('court', '').upper(),
            'location_1':     case.get('location_1', ''),
            'location_2':     case.get('location_2', ''),
        })

    return caption


def _build_appearances(attorneys):
    result = []
    for a in attorneys:
        by_raw = a.get('by', '')
        result.append({
            'role':         a.get('role', ''),
            'firm':         a.get('firm', '').upper(),
            'address_1':    a.get('address', ''),
            'city_state_zip': '',
            'attorneys':    [{'name': by_raw.upper()}],
        })
    return result


# ─────────────────────────────────────────────────────────────────────────────
# BUILD cr_config.json
# ─────────────────────────────────────────────────────────────────────────────

def build_cr_config(cr_profile, job_id):
    cr_id    = cr_profile['cr_id']
    state    = cr_profile.get('state', '')
    onboard  = cr_profile.get('onboarding_status', {})

    # Resolve module filenames from profile folder
    profile_dir = cr_dir(cr_id)
    state_mod   = f"STATE_MODULE_{cr_profile.get('state_module', '').replace('STATE_MODULE_', '')}"
    if not state_mod.endswith('.md'):
        state_mod += '.md'

    # Dictionary: only set if file actually exists in profile dir
    dict_path = os.path.join(profile_dir, 'dictionary.tlx')
    dictionary = 'dictionary.tlx' if os.path.exists(dict_path) else None

    return {
        'reporter_id':   cr_id,
        'reporter_name': cr_profile.get('cr_name', ''),
        'state_label':   cr_profile.get('practice_area', state),
        'formatter':     cr_profile.get('formatter', 'format_final.py'),
        'job_id':        job_id,
        'modules': {
            'state_module':   cr_profile.get('state_module', state_mod),
            'house_style':    f'HOUSE_STYLE_MODULE_{cr_id.split("_")[0]}.md',
            'knowledge_base': 'KNOWLEDGE_BASE_ny_wcb.txt' if state == 'NY' else 'KNOWLEDGE_BASE.txt',
            'dictionary':     dictionary,
        }
    }


# ─────────────────────────────────────────────────────────────────────────────
# STAGE RTF INTO ENGINE DIR
# ─────────────────────────────────────────────────────────────────────────────

def stage_modules(cr_id, cr_config):
    """
    Copy CR-specific KB and house style from profile dir into engine dir.
    Uses the engine-dir filenames from cr_config['modules'] so every script
    finds the right file without knowing which CR is loaded.

    State modules are shared engine resources — not copied here.
    """
    profile = cr_dir(cr_id)
    modules = cr_config.get('modules', {})

    copies = [
        ('KNOWLEDGE_BASE.txt',   modules.get('knowledge_base', 'KNOWLEDGE_BASE.txt')),
        ('HOUSE_STYLE_MODULE.md', modules.get('house_style',    f'HOUSE_STYLE_MODULE_{cr_id.split("_")[0]}.md')),
    ]

    for src_name, dest_name in copies:
        src  = os.path.join(profile, src_name)
        dest = os.path.join(ENGINE_DIR, dest_name)
        if not os.path.exists(src):
            print(f'  WARNING: {src_name} not found in profile dir — engine will use existing {dest_name}')
            continue
        shutil.copy2(src, dest)
        print(f'  [STAGE] {src_name} -> {dest_name}')


def stage_rtf(cr_id, job_id):
    """Copy RTF from intake/ into engine dir. Returns filename."""
    intake = intake_dir(cr_id, job_id)
    rtf_files = [f for f in os.listdir(intake) if f.lower().endswith('.rtf')]

    if not rtf_files:
        print('  ERROR: No RTF file found in intake/')
        sys.exit(1)
    if len(rtf_files) > 1:
        print(f'  WARNING: Multiple RTF files found — using {rtf_files[0]}')

    rtf_name = rtf_files[0]
    src  = os.path.join(intake, rtf_name)
    dest = os.path.join(ENGINE_DIR, rtf_name)
    shutil.copy2(src, dest)
    return rtf_name


# ─────────────────────────────────────────────────────────────────────────────
# UPDATE JOB STATUS
# ─────────────────────────────────────────────────────────────────────────────

def update_job_status(cr_id, job_id, rtf_name):
    status_path = os.path.join(job_dir(cr_id, job_id), 'JOB_STATUS.md')
    if not os.path.exists(status_path):
        return
    with open(status_path, 'r', encoding='utf-8') as f:
        content = f.read()
    content = content.replace(
        'Status:** INTAKE COMPLETE — ready to run',
        f'Status:** STAGED — engine ready, run command printed {datetime.now().strftime("%Y-%m-%d %H:%M")}'
    )
    with open(status_path, 'w', encoding='utf-8') as f:
        f.write(content)


# ─────────────────────────────────────────────────────────────────────────────
# WRITE
# ─────────────────────────────────────────────────────────────────────────────

def write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)


# ─────────────────────────────────────────────────────────────────────────────
# PREFLIGHT — walk the yard before anything runs
# ─────────────────────────────────────────────────────────────────────────────

def preflight(cr_id, job_id):
    print('\n  [PREFLIGHT] Walking the yard...')
    ok = True

    checks = [
        (os.path.join(cr_dir(cr_id), 'CR_PROFILE.json'),        'CR_PROFILE.json'),
        (os.path.join(intake_dir(cr_id, job_id), 'CASE_INFO.json'), 'intake/CASE_INFO.json'),
        (os.path.join(cr_dir(cr_id), 'HOUSE_STYLE_MODULE.md'),   'HOUSE_STYLE_MODULE.md'),
        (os.path.join(cr_dir(cr_id), 'KNOWLEDGE_BASE.txt'),      'KNOWLEDGE_BASE.txt'),
    ]

    for path, label in checks:
        exists = os.path.exists(path)
        mark = 'OK' if exists else 'MISSING'
        print(f'  [{mark}] {label}')
        if not exists:
            ok = False

    # RTF check
    intake = intake_dir(cr_id, job_id)
    rtf_files = [f for f in os.listdir(intake) if f.lower().endswith('.rtf')] if os.path.exists(intake) else []
    mark = 'OK' if rtf_files else 'MISSING'
    print(f'  [{mark}] RTF in intake/  {"(" + rtf_files[0] + ")" if rtf_files else "NOT FOUND"}')
    if not rtf_files:
        ok = False

    if not ok:
        print('\n  PREFLIGHT FAILED — fix missing items before staging.\n')
        sys.exit(1)

    print('  All checks passed.\n')


# ─────────────────────────────────────────────────────────────────────────────
# ENGINE CLEANUP — purge previous run artifacts before staging
# ─────────────────────────────────────────────────────────────────────────────

# Files the engine writes during a run — must be cleared before every new job.
# Leaving these causes the next run to inherit the previous depo's data.
RUN_ARTIFACTS = [
    'depo_config.json',                    # case config — locks to previous CR/case
    'audio_matches.json',                  # previous depo's audio validation results
    'audio_transcript.json',               # previous depo's Whisper transcript
    'audio_apply_log.json',               # previous audio apply decisions
    'line_map.json',                       # line numbers from previous depo's text
    'cleaned_text_FULL.txt',              # previous depo's full cleaned text
    'corrected_text.txt',                  # previous depo's AI output — precious but wrong here
    'corrected_text_pre_audio_backup.txt', # previous depo's backup
    'extracted_text.txt',                  # previous depo's raw extracted text
    'cleaned_text.txt',                    # previous depo's steno-cleaned text
    'correction_log.json',                 # previous AI correction log
    'verify_log.json',                     # previous verify pass log
    'specialist_verify_log.json',          # previous specialist verify log
    'ai_engine_checkpoint.json',           # previous AI checkpoint (prevents resume on wrong depo)
    'review_locations.json',              # previous review item locations
]

# Backup files — named with previous case — glob by pattern
BACKUP_PATTERNS = [
    'corrected_text_*_backup.txt',
    'CASE_CAPTION_*_backup.json',
]


def clean_engine_dir():
    """
    Remove previous run artifacts from engine dir.
    Called before staging — ensures stateless engine between jobs.
    Prints each file removed so there is a clear audit trail.
    """
    import glob
    print('  [CLEAN] Purging previous run artifacts...')
    removed = []
    skipped = []

    for filename in RUN_ARTIFACTS:
        path = os.path.join(ENGINE_DIR, filename)
        if os.path.exists(path):
            os.remove(path)
            removed.append(filename)
        else:
            skipped.append(filename)

    for pattern in BACKUP_PATTERNS:
        for path in glob.glob(os.path.join(ENGINE_DIR, pattern)):
            os.remove(path)
            removed.append(os.path.basename(path))

    if removed:
        for f in removed:
            print(f'  [CLEAN] Removed: {f}')
    else:
        print('  [CLEAN] Engine dir already clean.')

    # Also clean FINAL_DELIVERY — belongs to previous job
    delivery_dir = os.path.join(ENGINE_DIR, 'FINAL_DELIVERY')
    if os.path.exists(delivery_dir):
        import shutil as _shutil
        _shutil.rmtree(delivery_dir)
        print('  [CLEAN] Removed: FINAL_DELIVERY/')

    print()


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description='Stage a new depo job for the engine.')
    parser.add_argument('--cr',  required=True, help='CR ID  e.g. dalotto_ny_001')
    parser.add_argument('--job', required=True, help='Job ID e.g. fourman_wcb_20260324')
    args = parser.parse_args()

    cr_id  = args.cr
    job_id = args.job

    print(f'\n{"="*60}')
    print(f'  new_job.py — staging {job_id} for {cr_id}')
    print(f'{"="*60}')

    # 1. Preflight
    preflight(cr_id, job_id)

    # 2. Clean engine dir — remove all previous run artifacts
    clean_engine_dir()

    # 3. Load
    print('  [LOAD] Reading intake files...')
    case_info  = load_json(os.path.join(intake_dir(cr_id, job_id), 'CASE_INFO.json'), 'CASE_INFO.json')
    cr_profile = load_json(os.path.join(cr_dir(cr_id), 'CR_PROFILE.json'),           'CR_PROFILE.json')

    # 4. Build CASE_CAPTION.json → work/
    print('  [BUILD] Generating work/CASE_CAPTION.json...')
    caption = build_case_caption(case_info, cr_profile, job_id)
    caption_path = os.path.join(work_dir(cr_id, job_id), 'CASE_CAPTION.json')
    write_json(caption_path, caption)
    print(f'         Written: {caption_path}')

    # 4. Build cr_config.json → engine dir
    print('  [BUILD] Writing cr_config.json to engine...')
    config = build_cr_config(cr_profile, job_id)
    config_path = os.path.join(ENGINE_DIR, 'cr_config.json')
    write_json(config_path, config)
    print(f'         Written: {config_path}')

    # 5. Copy CASE_CAPTION into engine dir (engine reads it from its own dir)
    print('  [STAGE] Copying CASE_CAPTION.json to engine dir...')
    shutil.copy2(caption_path, os.path.join(ENGINE_DIR, 'CASE_CAPTION.json'))

    # 5b. Stage CR modules (KB + house style) from profile dir → engine dir
    print('  [STAGE] Staging CR modules (KB + house style)...')
    stage_modules(cr_id, config)

    # 6. Stage RTF
    print('  [STAGE] Copying RTF to engine dir...')
    rtf_name = stage_rtf(cr_id, job_id)
    print(f'         Staged: {rtf_name}')

    # 7. Update job status
    update_job_status(cr_id, job_id, rtf_name)

    # 8. Print run command
    work_path = work_dir(cr_id, job_id)
    print(f'\n{"="*60}')
    print('  STAGED. Run the pipeline:')
    print(f'\n    cd "{ENGINE_DIR}"')
    print(f'    python run_pipeline.py')
    print(f'\n  Work dir (outputs go here after run):')
    print(f'    {work_path}')
    print(f'\n  Blocking issues to resolve before delivery:')
    for item in cr_profile.get('open_questions', []):
        print(f'    • {item}')
    print(f'{"="*60}\n')


if __name__ == '__main__':
    main()
